#!/usr/bin/env bash
# Write a .env file from the current process environment (GitHub secrets/vars).
# Usage: ./scripts/write-env-file.sh [output-path]
set -euo pipefail

OUT="${1:-api/.env.local}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/.github/env.manifest.json"

export ROOT MANIFEST OUT
python3 <<'PY'
import json
import os
from pathlib import Path

root = Path(os.environ["ROOT"])
manifest = json.loads((root / ".github/env.manifest.json").read_text())
out_path = Path(os.environ["OUT"])

keys = sorted(
    set(manifest.get("secrets", []))
    | set(manifest.get("variables", []))
    | set(manifest.get("localOnly", []))
)

lines: list[str] = [
    "# Generated by scripts/write-env-file.sh — do not commit",
    "",
]

for key in keys:
    value = os.environ.get(key, "")
    if not value:
        continue
    if any(ch in value for ch in " #\"'$\\"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    else:
        lines.append(f"{key}={value}")

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {len(lines) - 2} keys to {out_path}")
PY
